# Generated by Django 2.0.6 on 2019-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('cityorigin', models.CharField(default='', max_length=200)),
                ('richpower', models.CharField(default='', max_length=200)),
                ('whichPower', models.CharField(default='', max_length=200)),
                ('goodEvil', models.CharField(default='', max_length=200)),
                ('examples', models.TextField(default='', max_length=50000000)),
            ],
        ),
    ]
